version: '3.7'

services:
  postgres:
    container_name: postgres-test
    image: postgres:12.1-alpine
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  default:
    name: test-network
    driver: bridge