server:
  port: 8080
springdoc:
  packages-to-scan: "ru.cft.project.loans.project_loans"
  paths-to-match: "/**"
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5439/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false