DROP TABLE IF EXISTS person;
CREATE TABLE person
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    surname         VARCHAR(255) NOT NULL,
    patronymics     VARCHAR(255),
    passport_series VARCHAR(255) NOT NULL,
    passport_number VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(255),
    email           VARCHAR(255),
    pts             VARCHAR(255)
);
